import localFont from "next/font/local";
import "./globals.css";
import MainLayout from "./components/mainLayout";
import Head from "next/head";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Poke Next",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" className="h-full">
      <head>
        <link rel="icon" href="/images/favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
